---
# Master playbook: oci-reporting-Yearly.yml
# Runs yearly reporting pipeline across all database types and stores into dedicated table.

- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/common.yml
  roles:
    - role: oci-reporting-yearly
